on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - uses: actions/checkout@v2
      - name: Clone intellij-community
        run: |
          git clone https://github.com/JetBrains/intellij-community.git /tmp/intellij-community
          cd /tmp/intellij-community
          git subtree push --prefix=plugins/java-decompiler/engine $GITHUB_WORKSPACE temp
      - name: Clone intellij-community
        run: |
          ls
          git branch
          git branch -r