on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - run: |
          mkdir intcomm
          cd intcomm
          git init
          git remote add -f intellij-community git@github.com:JetBrains/intellij-community.git
          git checkout master -- plugins/java-decompiler/engine
          ls
